name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main  # Run workflow when you push to main branch

jobs:
  deploy:
    name: Deploy CloudFormation
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Deploy CloudFormation stack
      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file vpc-subnets.yaml \
            --stack-name MyVPCStack \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset
